name: Projects-MD

on:
  push:
    branches: [ "main" ]
    paths:
      - projects.json
      - bin/generate-projects
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate MD
        run: source bin/generate-projects
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Projects
          file_pattern: 'projects.md'
