name: Projects-MD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Generate MD
        run: source bin/generate-projects
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update files
          file_pattern: 'projects.md'
